"""empty message

Revision ID: 3fe37244f205
Revises: 
Create Date: 2018-02-01 21:39:08.581585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe37244f205'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('baseSerial', sa.String(length=64), nullable=False),
    sa.Column('customer', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_baseSerial'), 'product', ['baseSerial'], unique=False)
    op.create_index(op.f('ix_product_customer'), 'product', ['customer'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_table('silicon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.String(length=64), nullable=False),
    sa.Column('productCode', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_silicon_codename'), 'silicon', ['codename'], unique=False)
    op.create_index(op.f('ix_silicon_description'), 'silicon', ['description'], unique=False)
    op.create_index(op.f('ix_silicon_productCode'), 'silicon', ['productCode'], unique=False)
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_name'), 'test', ['name'], unique=False)
    op.create_table('hardware_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipn', sa.String(length=64), nullable=False),
    sa.Column('reworkNumber', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardware_revision_ipn'), 'hardware_revision', ['ipn'], unique=False)
    op.create_table('product_silicon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('silicon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['silicon_id'], ['silicon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_serial'), 'sample', ['serial'], unique=False)
    op.create_table('software_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipn', sa.String(length=64), nullable=True),
    sa.Column('sw_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_component_ipn'), 'software_component', ['ipn'], unique=False)
    op.create_index(op.f('ix_software_component_sw_id'), 'software_component', ['sw_id'], unique=False)
    op.create_table('hardware_software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hw_revision_id', sa.Integer(), nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hw_revision_id'], ['hardware_revision.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software_component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_hardware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('hw_revision_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hw_revision_id'], ['hardware_revision.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('software_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reworkNumber', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['software_component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('hardware_revision_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hardware_revision_id'], ['hardware_revision.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['testid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('value', sa.String(length=64), nullable=True),
    sa.Column('attribute', sa.String(length=64), nullable=True),
    sa.Column('datatype', sa.String(length=64), nullable=True),
    sa.Column('test_run', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_run'], ['testrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testdata')
    op.drop_table('testrun')
    op.drop_table('testid')
    op.drop_table('software_revision')
    op.drop_table('sample_hardware')
    op.drop_table('hardware_software')
    op.drop_index(op.f('ix_software_component_sw_id'), table_name='software_component')
    op.drop_index(op.f('ix_software_component_ipn'), table_name='software_component')
    op.drop_table('software_component')
    op.drop_index(op.f('ix_sample_serial'), table_name='sample')
    op.drop_table('sample')
    op.drop_table('product_silicon')
    op.drop_index(op.f('ix_hardware_revision_ipn'), table_name='hardware_revision')
    op.drop_table('hardware_revision')
    op.drop_index(op.f('ix_test_name'), table_name='test')
    op.drop_table('test')
    op.drop_index(op.f('ix_silicon_productCode'), table_name='silicon')
    op.drop_index(op.f('ix_silicon_description'), table_name='silicon')
    op.drop_index(op.f('ix_silicon_codename'), table_name='silicon')
    op.drop_table('silicon')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_customer'), table_name='product')
    op.drop_index(op.f('ix_product_baseSerial'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
